/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.helmo.gbeditor;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import org.helmo.gbeditor.domains.CanCreateGameBookSession;
import org.helmo.gbeditor.domains.Session;
import org.helmo.gbeditor.infrastructures.jdbc.UpdateHandler;
import org.helmo.gbeditor.repositories.ConnectionData;
import org.helmo.gbeditor.infrastructures.jdbc.MySQLConnectionData;
import org.helmo.gbeditor.infrastructures.jdbc.SqlProjectStorageFactory;
import org.helmo.gbeditor.presentations.*;
import org.helmo.gbeditor.repositories.IFactory;
import org.helmo.gbeditor.repositories.IUpdateHandler;
import org.helmo.gbeditor.views.*;

/**
 * La classe App permet à un utilisateur de créer et gérer un livre-jeu
 */
public class App extends Application {

    /**
     * La méthode main permet de lancer l'application de livre-jeu
     * @param args
     */
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        JavaFXViewInterface mainView = buildViews();

        Parent root = mainView.getRoot();

        Scene scene = new Scene(root,690,590);
        scene.getStylesheets().add(getClass().getResource("/styles.css").toExternalForm());
        primaryStage.setTitle("GameBook");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    private JavaFXViewInterface buildViews() {
        CanCreateGameBookSession currentSession = new Session();
        ConnectionData connection = new MySQLConnectionData();
        UpdateHandler updateHandler = new UpdateHandler();
        IFactory factory = new SqlProjectStorageFactory(connection,updateHandler);

        return buildMainView(currentSession,buildLoginView(currentSession,factory),buildWelcomeView(currentSession,factory),buildCreateBookView(currentSession,factory),buildEditBookView(currentSession,factory,updateHandler),buildAddPageView(currentSession),buildEditPageView(currentSession),buildAddChoiceView(currentSession));
    }

    private JavaFXViewInterface buildMainView(CanCreateGameBookSession currentSession,JavaFXViewInterface ...views)  {
        JavaFXViewInterface mainView = new MainView(views);
        new MainPresenter(mainView,currentSession);
        return mainView;
    }

    private JavaFXViewInterface buildLoginView(CanCreateGameBookSession currentSession,IFactory factory) {
        JavaFXViewInterface loginView = new LoginView();
        new LoginPresenter(loginView,currentSession,factory);
        return loginView;
    }

    private JavaFXViewInterface buildWelcomeView(CanCreateGameBookSession currentSession,IFactory factory) {
        JavaFXViewInterface welcomeView = new WelcomeView();
        new WelcomePresenter(welcomeView,currentSession,factory);
        return welcomeView;
    }

    private JavaFXViewInterface buildCreateBookView(CanCreateGameBookSession currentSession,IFactory factory) {
        JavaFXViewInterface createBookView = new CreateBookView();
        new CreateBookPresenter(createBookView,currentSession,factory);
        return createBookView;
    }

    private JavaFXViewInterface buildEditBookView(CanCreateGameBookSession currentSession, IFactory factory, IUpdateHandler updateHandler) {
        JavaFXViewInterface editBookView = new EditBookView();
        new EditBookPresenter(editBookView,currentSession,factory,updateHandler);
        return editBookView;
    }

    private JavaFXViewInterface buildAddPageView(CanCreateGameBookSession currentSession) {
        JavaFXViewInterface addPageView = new AddPageView();
        new AddPagePresenter(addPageView,currentSession);
        return addPageView;
    }

    private JavaFXViewInterface buildEditPageView(CanCreateGameBookSession currentSession) {
        JavaFXViewInterface editPageView = new EditPageView();
        new EditPagePresenter(editPageView,currentSession);
        return editPageView;
    }

    private JavaFXViewInterface buildAddChoiceView(CanCreateGameBookSession currentSession) {
        JavaFXViewInterface addChoiceView = new AddChoiceView();
        new AddChoicePresenter(addChoiceView,currentSession);
        return addChoiceView;
    }

}
